/*
* Purpose: Support code-generation activities with templates
*/
const { readFileSync } = require('fs')

const TemplateToken = {
    BANNER: '<% banner %>',
    IMPORTS: '<% imports %>',
    EXPORTS: '<% exports %>',
    TAG: '<% tag %>',
    COMPONENT_CLASS_NAME: '<% component-class-name %>',
    PROPERTIES: '<% properties %>',
    ATTRIBUTES: '<% attributes %>',
    EVENTS: '<% events %>'
}

const GENERATED_CODE_BANNER = `/*
* DO NOT EDIT THIS FILE. IT IS GENERATED
*/`
const templatesFolder = `${__dirname}/templates`
const getTemplate = (template, language) =>
    readFileSync(`${templatesFolder}/${language}/${template}.tmpl`, { encoding: 'utf8' })
        .replace(TemplateToken.BANNER, GENERATED_CODE_BANNER)

module.exports = {
    getTemplate,
    TemplateToken,
    GENERATED_CODE_BANNER
}