name: publish to package registries

on:
  workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: publish to npmjs.com
        run: |
          echo registry=https://registry.npmjs.org/ > .npmrc
          echo //registry.npmjs.org/:_authToken=${TOKEN} >> .npmrc
          npm publish --access public --//registry.npmjs.org/:_authToken=$TOKEN
        env:
          TOKEN: ${{secrets.NPM_TOKEN}} # token has been issued on January 4, 2023. It's valid for 1 year

      - name: publish to github.com
        run: |
          echo registry=https://npm.pkg.github.com/ > .npmrc
          echo //npm.pkg.github.com/:_authToken=${TOKEN} >> .npmrc
          npm publish --access public
        env:
          TOKEN: ${{github.token}}
